FROM pytorch/pytorch:2.0.1-cuda11.7-cudnn8-runtime

WORKDIR /app
RUN pip install --no-cache-dir torchvision fastapi uvicorn pillow

COPY serve.py /app/serve.py
ENV MODEL_TYPE=pretrained

EXPOSE 8080
CMD ["uvicorn", "serve:app", "--host", "0.0.0.0", "--port", "8080"]
